# This is a basic workflow to help you get started with Actions

name: Publish to Nuget

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
            5.0.x
            6.0.x
          include-prerelease: true
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Pack
        run: dotnet pack -o publishOutput --no-restore --no-build --verbosity normal

      # Runs a set of commands using the runners shell
      - name: Push to Nuget
        env:
          NUGET_UPDATEKEY: ${{ secrets.NUGET_UPDATEKEY }}
        run: dotnet nuget push publishOutput/*.nupkg -k $NUGET_UPDATEKEY
