name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'
  workflow_dispatch:

jobs:
  Tests:
  
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          5.0.x
          6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c ${{ matrix.configuration }} --no-restore
    - name: Test
      run: dotnet test -c ${{ matrix.configuration }} --no-build --verbosity normal
